name: Build Release APK

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Set up Android SDK with specific API level and build tools
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: "34.0.0"

      # 4. Make Gradle Wrapper executable
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      # 5. Build release APK
      - name: Build Release APK
        run: ./gradlew clean assembleRelease

      # 6. Locate APK
      - name: Locate built APK
        run: |
          APK_PATH=$(find $GITHUB_WORKSPACE/app/build/outputs/apk/release -name '*.apk' | head -n 1)
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
          echo "Located APK at: $APK_PATH"

      # 7. Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: LostModeClient-APK
          path: ${{ env.APK_PATH }}