name: Build and Sign Release APK

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Set up JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Set up Android SDK with explicit API level and build tools
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: "34.0.0"

      # 4. Make Gradle Wrapper executable
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      # 5. Build release APK
      - name: Build Release APK
        run: ./gradlew clean assembleRelease

      # 6. Locate unsigned APK
      - name: Locate unsigned APK
        run: |
          APK_UNSIGNED=$(find $GITHUB_WORKSPACE/app/build/outputs/apk/release -name '*-unsigned.apk' | head -n 1)
          echo "APK_UNSIGNED=$APK_UNSIGNED" >> $GITHUB_ENV
          echo "Unsigned APK: $APK_UNSIGNED"

      # 7. Generate debug keystore (for signing; replace with production keystore if needed)
      - name: Generate debug keystore
        run: |
          keytool -genkey -v \
            -keystore debug.keystore \
            -alias lostmodekey \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass android \
            -keypass android \
            -dname "CN=LostMode, OU=Dev, O=LostMode, L=City, ST=State, C=US"

      # 8. Sign APK using correct apksigner path
      - name: Sign APK
        run: |
          $ANDROID_SDK_ROOT/build-tools/34.0.0/apksigner sign \
            --ks debug.keystore \
            --ks-key-alias lostmodekey \
            --ks-pass pass:android \
            --key-pass pass:android \
            --out $GITHUB_WORKSPACE/app/build/outputs/apk/release/app-release-signed.apk \
            $APK_UNSIGNED

      # 9. Align APK for installation
      - name: Align APK
        run: |
          $ANDROID_SDK_ROOT/build-tools/34.0.0/zipalign -v 4 \
            $GITHUB_WORKSPACE/app/build/outputs/apk/release/app-release-signed.apk \
            $GITHUB_WORKSPACE/app/build/outputs/apk/release/app-release-aligned.apk

      # 10. Upload aligned APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: LostModeClient-APK
          path: $GITHUB_WORKSPACE/app/build/outputs/apk/release/app-release-aligned.apk
